services:
    nginx:
        image: nginx:alpine
        container_name: shipping_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        networks:
            - shipping_network

    php:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: shipping_php
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - shipping_network
        environment:
            APP_ENV: dev
            APP_DEBUG: "1"

    frontend:
        image: node:20-alpine
        container_name: shipping_frontend
        working_dir: /var/www/html/assets
        volumes:
            - .:/var/www/html
        command: sh -c "npm install && npm run build -- --host"
        networks:
            - shipping_network

networks:
    shipping_network:
        driver: bridge
